#!/bin/bash
current_time=$(date "+%Y%m%d%H%M%S")

mkdir ./BUILD_LINUx64/


cp -r ../data ./BUILD_LINUx64/

gcc ../main.c -o ./BUILD_LINUx64/1964.AppImage -lGL -L./raylib/linux64 -l:libraylib.a -lm -lpthread -ldl -lrt -lX11&&chmod +x ./BUILD_LINUx64/1964.AppImage
